#!/usr/bin/env bash
# Install stub headers required by libslic3r that are not provided by any
# dedicated build script. These are:
#
#   1. libseqarrange/seq_interface.hpp — stub for Z3/libseqarrange types
#      (ArrangeHelper.hpp is included by Print.cpp; our stub cpp satisfies
#       the linker without Z3)
#   2. nlopt.h — NLopt optimizer header (SLA only, never called in FDM path)
#   3. nanosvg/nanosvg.h + nanosvgrast.h — SVG headers (fltk fork, used by
#      EmbossShape.hpp, not in the FDM slicing path)
#   4. libslic3r_version.h — generated by cmake during libslic3r build;
#      the Xcode compile needs it in the sysroot include path
#   5. semver/semver.h — bundled semver header
#   6. PrusaSlicer bundled_deps headers — admesh, ankerl, agg, fast_float,
#      glu-libtess, imgui, int128, libigl, libnest2d, localesutils, miniz,
#      qoi, stb_dxt, stb_image, tcbspan — all header-only, needed by the
#      Xcode compile of slicer_bridge.cpp
#
# Run AFTER 02_prusaslicer.sh (source tree) and 10_libslic3r.sh (build dir).
source "$(dirname "$0")/common.sh"
require_sysroot

SENTINEL="$IOS_SYSROOT/include/libseqarrange/seq_interface.hpp"
already_done "$SENTINEL" && exit 0

if [ ! -d "$PRUSA_SRC/.git" ]; then
    log_error "PrusaSlicer not cloned. Run 02_prusaslicer.sh first."
    exit 1
fi

LIBSLIC3R_BUILD="$IOS_SOURCES/libslic3r-build-ios-sim"

log_step "Installing stub headers into sysroot"

# ── 1. libseqarrange stub ─────────────────────────────────────────────────
mkdir -p "$IOS_SYSROOT/include/libseqarrange"
cat > "$IOS_SYSROOT/include/libseqarrange/seq_interface.hpp" << 'ENDHPP'
// iOS stub: libseqarrange/seq_interface.hpp
// Provides Sequential type definitions without Z3 / libseqarrange.
#pragma once
#include <stdexcept>
#include <functional>
#include <optional>
#include <vector>
#include <set>
#include <map>
#include <string>
#include <cstdint>

// Forward-declare the Slic3r types we need to avoid include-order issues.
namespace Slic3r {
    class Polygon;
    class BoundingBox;
}

namespace Sequential {

class ObjectTooLargeException : public std::runtime_error {
public:
    explicit ObjectTooLargeException(const std::string& msg) : std::runtime_error(msg) {}
};

struct PrinterGeometry {
    Slic3r::Polygon* _plate = nullptr;
    std::set<int32_t> convex_heights;
    std::set<int32_t> box_heights;
    bool convert_Geometry2PlateBounds(Slic3r::BoundingBox&, Slic3r::Polygon&) const { return false; }
};

enum DecimationPrecision {
    SEQ_DECIMATION_PRECISION_UNDEFINED,
    SEQ_DECIMATION_PRECISION_LOW,
    SEQ_DECIMATION_PRECISION_HIGH
};

struct SolverConfiguration {
    SolverConfiguration() = default;
    SolverConfiguration(const PrinterGeometry&) {}
    void set_DecimationPrecision(DecimationPrecision) {}
    void set_ObjectGroupSize(int) {}
    void setup(const PrinterGeometry&) {}
    static double convert_DecimationPrecision2Tolerance(DecimationPrecision) { return 0.0; }

    int bounding_box_size_optimization_step = 0;
    int minimum_bounding_box_size = 0;
    Slic3r::BoundingBox* _bbox = nullptr;
    Slic3r::Polygon*     _plate = nullptr;
    int max_refines = 0;
    int object_group_size = 0;
    int fixed_object_grouping_limit = 0;
    int temporal_spread = 0;
    DecimationPrecision decimation_precision = SEQ_DECIMATION_PRECISION_UNDEFINED;
    std::string optimization_timeout;
};

struct ObjectToPrint {
    int id = 0;
    bool glued_to_next = false;
    int32_t total_height = 0;
};

struct ScheduledObject {
    ScheduledObject(int _id, int32_t _x, int32_t _y) : id(_id), x(_x), y(_y) {}
    int id = 0;
    int32_t x = 0, y = 0;
};

struct ScheduledPlate {
    std::vector<ScheduledObject> scheduled_objects;
};

inline bool check_ScheduledObjectsForSequentialPrintability(
    const SolverConfiguration&, const PrinterGeometry&,
    const std::vector<ObjectToPrint>&, const std::vector<ScheduledPlate>&)
{ return true; }

inline std::optional<std::pair<int,int>> check_ScheduledObjectsForSequentialConflict(
    const SolverConfiguration&, const PrinterGeometry&,
    const std::vector<ObjectToPrint>&, const std::vector<ScheduledPlate>&)
{ return std::nullopt; }

inline std::vector<ScheduledPlate> schedule_ObjectsForSequentialPrint(
    const SolverConfiguration&, const PrinterGeometry&,
    const std::vector<ObjectToPrint>&, std::function<void(int)> = [](int){})
{ return {}; }

inline void schedule_ObjectsForSequentialPrint(
    const SolverConfiguration&, const PrinterGeometry&,
    const std::vector<ObjectToPrint>&, std::vector<ScheduledPlate>&,
    std::function<void(int)> = [](int){}) {}

} // namespace Sequential
ENDHPP
log_ok "libseqarrange/seq_interface.hpp installed"

# ── 2. nlopt.h ────────────────────────────────────────────────────────────
# NLopt 2.5.0 header: used only by SLA, never linked in FDM path.
if [ ! -f "$IOS_SYSROOT/include/nlopt.h" ]; then
    NLOPT_VER="2.5.0"
    NLOPT_TAR="$IOS_SOURCES/nlopt-${NLOPT_VER}.tar.gz"
    if [ ! -f "$NLOPT_TAR" ]; then
        curl -L "https://github.com/stevengj/nlopt/archive/v${NLOPT_VER}.tar.gz" \
             -o "$NLOPT_TAR"
    fi
    cd "$IOS_SOURCES"
    tar xf "$NLOPT_TAR" "nlopt-${NLOPT_VER}/src/api/nlopt.h" --strip-components=3 2>/dev/null || \
    tar xf "$NLOPT_TAR" --strip-components=3 "nlopt-${NLOPT_VER}/src/api/nlopt.h" 2>/dev/null || \
    (tar xf "$NLOPT_TAR" && cp "nlopt-${NLOPT_VER}/src/api/nlopt.h" "$IOS_SYSROOT/include/nlopt.h" && rm -rf "nlopt-${NLOPT_VER}")
    [ -f "nlopt.h" ] && mv "nlopt.h" "$IOS_SYSROOT/include/nlopt.h"
    log_ok "nlopt.h installed"
fi

# ── 3. nanosvg headers ────────────────────────────────────────────────────
# fltk/nanosvg fork used by EmbossShape.hpp
if [ ! -f "$IOS_SYSROOT/include/nanosvg/nanosvg.h" ]; then
    NANOSVG_SRC="$IOS_SOURCES/nanosvg"
    if [ ! -d "$NANOSVG_SRC" ]; then
        git clone --depth 1 https://github.com/fltk/nanosvg.git "$NANOSVG_SRC"
    fi
    mkdir -p "$IOS_SYSROOT/include/nanosvg"
    cp "$NANOSVG_SRC/src/nanosvg.h"     "$IOS_SYSROOT/include/nanosvg/"
    cp "$NANOSVG_SRC/src/nanosvgrast.h" "$IOS_SYSROOT/include/nanosvg/"
    log_ok "nanosvg headers installed"
fi

# ── 4. libslic3r_version.h ────────────────────────────────────────────────
# Generated by cmake; copy from build dir into sysroot so Xcode can find it.
VERSION_H="$LIBSLIC3R_BUILD/src/libslic3r/libslic3r_version.h"
if [ -f "$VERSION_H" ]; then
    cp "$VERSION_H" "$IOS_SYSROOT/include/libslic3r/libslic3r_version.h"
    log_ok "libslic3r_version.h installed"
elif [ ! -f "$IOS_SYSROOT/include/libslic3r/libslic3r_version.h" ]; then
    # Fallback: write a static version header matching the cloned PrusaSlicer
    PRUSA_VER=$(grep -m1 'set.*SLIC3R_VERSION' "$PRUSA_SRC/CMakeLists.txt" 2>/dev/null | \
                grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || echo "2.9.4")
    mkdir -p "$IOS_SYSROOT/include/libslic3r"
    cat > "$IOS_SYSROOT/include/libslic3r/libslic3r_version.h" << ENDVER
#ifndef __SLIC3R_VERSION_H
#define __SLIC3R_VERSION_H

#define SLIC3R_APP_NAME "PrusaSlicer"
#define SLIC3R_APP_KEY "PrusaSlicer"
#define SLIC3R_VERSION "${PRUSA_VER}"
#define SLIC3R_BUILD_ID "PrusaSlicer-${PRUSA_VER}+UNKNOWN"

#endif /* __SLIC3R_VERSION_H */
ENDVER
    log_ok "libslic3r_version.h (static fallback) installed → $PRUSA_VER"
fi

# ── 5. semver headers ─────────────────────────────────────────────────────
if [ ! -f "$IOS_SYSROOT/include/semver/semver.h" ] && \
   [ ! -f "$IOS_SYSROOT/include/semver.h" ]; then
    SEMVER_SRC="$PRUSA_SRC/bundled_deps/semver"
    if [ -d "$SEMVER_SRC" ]; then
        mkdir -p "$IOS_SYSROOT/include/semver"
        cp "$SEMVER_SRC"/*.h "$IOS_SYSROOT/include/semver/" 2>/dev/null || true
        # Also install at root level (some includes use #include "semver.h")
        cp "$SEMVER_SRC"/*.h "$IOS_SYSROOT/include/" 2>/dev/null || true
        log_ok "semver headers installed"
    fi
fi

# ── 6. PrusaSlicer bundled_deps headers ───────────────────────────────────
BUNDLED="$PRUSA_SRC/bundled_deps"
log_step "Installing PrusaSlicer bundled_deps headers"

install_dir() {
    local src="$BUNDLED/$1"
    local dst="$IOS_SYSROOT/include/$1"
    if [ -d "$src" ]; then
        mkdir -p "$dst"
        cp -Rn "$src/." "$dst/" 2>/dev/null || true
    fi
}

install_dir admesh
install_dir agg
install_dir ankerl
install_dir avrdude
install_dir fast_float
install_dir glu-libtess
install_dir hidapi
install_dir imgui
install_dir int128
install_dir libigl
install_dir libnest2d
install_dir localesutils
install_dir miniz
install_dir qoi
install_dir stb_dxt
install_dir stb_image
install_dir tcbspan

log_ok "bundled_deps headers installed"
log_ok "All stub headers installed to $IOS_SYSROOT/include/"
